# Generated by Django 5.0.4 on 2024-04-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_position_employees_employment_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='start_date',
            field=models.DateField(),
        ),
    ]
