# Generated by Django 5.0.4 on 2024-04-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employees_employment_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='date_added',
        ),
    ]
