# Generated by Django 5.0.4 on 2024-04-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employees_employment_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='ФИО'),
        ),
    ]
