# Generated by Django 5.0.4 on 2024-05-08 14:29

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employees_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employment_position',
            field=models.CharField(max_length=200, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='employees.employees', verbose_name='Supervisor'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='start_date',
            field=models.DateField(verbose_name='Start_date'),
        ),
    ]
