# Generated by Django 5.0.4 on 2024-05-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employees_employment_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/%Y/%m/%d', verbose_name='employment_photo'),
        ),
    ]
