# Generated by Django 5.0.4 on 2024-05-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='employees_photo', verbose_name='photo'),
        ),
    ]
