# Generated by Django 5.0.4 on 2024-05-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_employees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, default='employees_photo/1.jpg', upload_to='images/%Y/%m/%d'),
        ),
    ]
