# Generated by Django 5.0.4 on 2024-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_employees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, default='employees_photo/jack_of_hearts.jpg', upload_to='employees_photo'),
        ),
    ]
