# Generated by Django 5.0.4 on 2024-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_alter_employees_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, default='employees_photo/jack_of_hearts.jpg', null=True, upload_to='images/'),
        ),
    ]
